# Generated by Django 4.1.3 on 2022-11-17 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CBV', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Car_category',
        ),
    ]
